language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
  - 10
  - 8
  - 6
before_install:
  - 'npm i -g npm@latest'
after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
